# Generated by Django 6.0.5 on 2026-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_meditationsession_meditation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='compeleted',
            field=models.BooleanField(default=False),
        ),
    ]
