# Generated by Django 6.0.5 on 2026-05-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_meditationsession_compeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meditationsession',
            old_name='compeleted',
            new_name='completed',
        ),
    ]
